steps:
  - uses: actions/checkout@v4
  - uses: subosito/flutter-action@v2
    with:
      flutter-version: '3.19.0'
  
  # AGREGA ESTE PASO AQUÍ:
  - name: Get Dependencies
    run: flutter pub get

  - name: Build APK Release
    run: flutter build apk --release
